apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: default
spec:
  dnsNames:
    - $DOMAIN_NAME
  secretName: $DOMAIN_NAME
  issuerRef:
    name: letsencrypt-prod