apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $APPLICATION_NAME
  namespace: argocd
spec:
  project: default
  source:
    repoURL: $REPOSITORY_URL
    targetRevision: HEAD
    path: $PATH_TO_OPENAPI
    plugin:
      name: kusk-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default