apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: web-app-sample
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  upstream:
    service:
      name: oauth-app-svc
      namespace: default
      port: 3000
  auth:
    scheme: oauth2
    oauth2:
      token_endpoint: https://$AUTH0_DOMAIN/oauth/token
      authorization_endpoint: https://$AUTH0_DOMAIN/authorize
      credentials:
        client_id: $CLIENT_ID
        client_secret: $CLIENT_SECRET
      redirect_uri: /oauth2/callback
      redirect_path_matcher: /oauth2/callback
      signout_path: /oauth2/signout
      forward_bearer_token: true
      auth_scopes:
        - openid
        - profile
        - email
